### ISSUE TITLE
Break up MPA layers with multiple colors

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#17]
Nick's work 
- [x] MPAs only exist in OR and CA. 
- [x] the RCA is not the same thing and should have its own layer
- [ ] The aggregate layers should have visual distinction and legends to clarify where the pieces are coming from
- [ ] The styling should include labels if possible.

Nick:
- [x] Gather .shp files and list location in the comments
- [x] Generate .xml files and list location in the comments
- [x] Generate legend .png files and list location in the comments

Ryan:
- [x] Upload .shp and .xml files to appropriate place on tile server
- [x] Configure .xml file
- [x] Configure tilestache
- [x] Add layers to tool and test
- [x] check in legend
- [x] Add legend to tool

**Comment by ghost** [comment]
State MPAs are ready-

spatial data:
\neoterra\GIS\projects\PewEFH2015\Data\Processed\PEW_final_datasets\Marine_regulations\MPAs_state_OR_CA.shp

xml: \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_state_MPAs_OR_CA.xml

legend:
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Legend_pngs\PEW_state_MPAs_OR_CA.png
