### ISSUE TITLE
Change color ramp on Surficial Geology Layer

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#24]
From Jon:
we need to update the color ramp as the current layer washes out too much. I think this was on the list of edits we discussed but if not please add it to the mix and lets address it

Nick:
- [x] Generate .xml files and list location in the comments
- [x] Generate legend .png files and list location in the comments

Ryan:
- [x] Upload .shp and .xml files to appropriate place on tile server
- [x] Configure .xml file
- [x] Configure tilestache
- [x] Add layers to tool and test
- [x] check in legend
- [x] Add legend to tool

**Comment by ghost** [comment]
The color ramp for substrate was updated from grays to browns.  I will close this unless it needs to be addressed again after review.

**Comment by rhodges** [comment]
Nick - please point me at the new XML and legend image, then assign this to me so I can put it up on the site.

**Comment by ghost** [comment]
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_substrate.xml

**Comment by ghost** [comment]
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Legend_pngs\PEW_substrate.png
