### ISSUE TITLE
Add new NOAA DSCRTP observations

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#26]
NOAA DSCRTP additional new observations both inside and outside 3500 meters (We have outside 3500 meters – lets add soon, see attached to email from Jon ~2:00 PM, July 6th)

**Comment by ghost** [comment]
Ryan, I have added the .xml for this dataset called "PEW_NOAA_corals_sponges_below_3500m".  I have enabled the teaser for this to display what was observed utilizing the UTF grid.  
The shapefile is here: \NEOTERRA\gis\projects\PewEFH2015\Data\Processed\PEW_final_datasets\Corals_and_sponges\NOAA_DSCRTP_corals_below_3500m.shp.

**Comment by ghost** [comment]
Hey Ryan,

I added the two coral and sponge point dataset legends to associate.  They can be found here: \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Legend_pngs
