### ISSUE TITLE
Split shrimp effort time series

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#29]
See here:  http://www.pcouncil.org/wp-content/uploads/2015/03/IR6_NMFS_PinkShrimpVMS_APR2015BB.pdf 

Nick:
- [x] Gather .shp files and list location in the comments
- [x] Generate .xml files and list location in the comments
- [x] Generate legend .png files and list location in the comments

Ryan:
- [x] Upload .shp and .xml files to appropriate place on tile server
- [x] Configure .xml file
- [x] Configure tilestache
- [x] Add layers to tool and test
- [x] check in legend
- [x] Add legend to tool

**Comment by ghost** [comment]
Hi Ryan, I have updated the pink shrimp data and created two new .xmls and two new legends.

The .xmls:
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_pink_shrimp_VMS_2009_2013.xml
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_pink_shrimp_VMS_2011_2013.xml

The spatial datasets:
\neoterra\GIS\projects\PewEFH2015\Data\Processed\PEW_final_datasets\Fishing_effort\Pink_shrimp\Shrimp VMS Footprint Aggregation 2009-2013.shp
\neoterra\GIS\projects\PewEFH2015\Data\Processed\PEW_final_datasets\Fishing_effort\Pink_shrimp\Shrimp VMS Footprint Aggregation 2011-2013.shp

**Comment by ghost** [comment]
Ryan,
The existing file on Marine Planner regarding pink shrimp VMS displays 2009-2013 data.  There is a new .xml with data from 2011-2013 that needs to be uploaded.  There is a legend file for them too.
