### ISSUE TITLE
Break out 3NM Line as separate Layer

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#30]
- [x] Make the Shapefile
- [x] Style the layer (mapnik XML)
- [x] Install on Tile Server [ Ryan ]
- [x] Include in Tool [ Ryan ]
  Nick: When you make the layer, put a link here and assign this ticket to Me.

**Comment by ghost** [comment]
Hey Ryan, there are 2 shapefiles for this dataset:
\NEOTERRA\gis\projects\PewEFH2015\Deliverables\Data\Spatial_data\Marine_boundaries\3_nm_line.shp
\NEOTERRA\gis\projects\PewEFH2015\Deliverables\Data\Spatial_data\Marine_boundaries\3_nm_islands.shp

The .xml is here: 
\NEOTERRA\gis\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_3nm_limit.xml
