### ISSUE TITLE
Create Oregon surficial geology layer without inferred rock [ 2 hours ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#35]
- [x] Find new layer or alter current layer
- [ ] create new stand-alone inferred rock layer
- [x] ascertain, quatify, and display level of confidence

Not a deal-breaker if doesn't fit into the budget

**Comment by ghost** [comment]
Hey Ryan,

I ended up using the same dataset for the surficial geology (previously titled "Substrate") and incorporated the "inferred rock" with "probably hard".  The "inferred rock" was only available for Oregon and was determined by slopes greater than 10 degrees.  The .xml is here: \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_substrate.xml
The legend png is here: \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Legend_pngs\PEW_substrate.png
The spatial data is here: \neoterra\GIS\projects\PewEFH2015\Data\Processed\PEW_final_datasets\Substrate\  The .xml references wa_sub_poly.shp, or_sub_poly.shp, ca_sub_poly.shp, and reg_merged_sub_poly.shp.  Let me know if you have any questions.

**Comment by rhodges** [comment]
New layers, style, and legend are in place. I'm calling this one "done enough"
