### ISSUE TITLE
New UTF Popup Layers [ 8 hours ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#36]
- [x] EFH
- [x] collaborative proposal
- [x] Oceana
- [x] change coalition proposal to: "NGO Industry Collaborative"
- Oceana Only EFH
- ID
- Name
- cpfv/fish (type of closure)
- area in SQ Mi.
- opening or closure

**Comment by rhodges** [comment]
- [x] Need a UTF live server. 

--- now serves as own UTF Grid server ---

Where?!
I think I'm currently bumming off of Juniper or something crazy like that.
- [x] Need: link to notes for generating UTF tiles.

Try [your own wiki](https://github.com/Ecotrust/PEW-EFH/wiki/Serving-UTF-Grid-Tiles)

**Comment by rhodges** [comment]
Need check for long-int maximum exceeded for 'area in SQ Mi.' on following .shps:
- [x] PHS all
- [x] State MPAs (OR & CA)
- [x] EFH Proposed Closures ("conservation areas"?)
- [x] Collaborative Proposed Closures
- [x] Oceana proposed closures

**Comment by ghost** [comment]
All of the datasets above have an updated "Area_m2" double field.  Some of them didn't have it prior, but they all have it now.  All of the datasets are in the same location as before, so perhaps a hard refresh/clear cache will work?  Let me know if you need anything else for this.
