### ISSUE TITLE
Update Coral/Sponge Observation Layers/Styles

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#43]
Nick: Add location and description here.

**Comment by ghost** [comment]
Hey Ryan, the new coral and sponge .xmls and shapefiles are listed below: 
xml 1 - \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_NOAA_All_Coral_Sponge_Observations.xml
xml 2 - 
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_NOAA_All_Coral_Sponge_Observations_below_3500m.xml

shapefile 1a -
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Spatial_data\Corals_and_sponges\NOAA_corals_EEZ.shp
shapefile 1b -
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Spatial_data\Corals_and_sponges\NOAA_corals_EEZ_w_counts.shp
shapefile 2a - 
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Spatial_data\Corals_and_sponges\NOAA_corals_dt_3500m.shp
shapefile 2b - 
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Spatial_data\Corals_and_sponges\NOAA_corals_dt_3500m_w_counts.shp

legend 1 - 
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Legend_pngs\PEW_NOAA_All_Coral_and_Sponge_Observations.PNG
legend 2 - 
\neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Legend_pngs\PEW_NOAA_all_corals_sponges_below_3500m.PNG

If this is confusing, let me know and I can help point you to where things need to be associated.

**Comment by rhodges** [comment]
Complete: 9a8797a901f3c34aaf03afa40505cb5bfcc479e6
