### ISSUE TITLE
Add new NGO Collab Layer

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/PEW-EFH#48]
Nick:
- [x] shapefile
- [x] mapnik xml
- [x] mbtiles
- [x] metadata xml

Ryan:
- [x] serve from tile server
- [x] serve UTF grid
- [x] Add layer to tool
  - [x] view
  - [x] click attributes
  - [x] metadata
- [x] test

**Comment by ghost** [comment]
Nick:

 shapefile - \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Spatial_data\EFH_proposals\EFH_proposal_open_close_v2.shp
 mapnik xml - \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Mapnik_xml\PEW_EFH_proposal_open_close_v2.xml
 metadata xml - \neoterra\GIS\projects\PewEFH2015\Deliverables\Data\Metadata_xml\EFH_proposal_open_close_v2.shp.xml
